### ISSUE TITLE
Connection to redis server hangs. 

### ISSUE THREAD

**Issue by BarrySlyDelgado** [BarrySlyDelgado/merlin#3]
@bgunnar5 I think we communicate here on development with Merlin and TaskVine.

Ive been able to get a results Redis server running here at Notre Dame. However when trying to do oprations with that Redis connection it just hangs. i.e `redis_conn.hset()` 

Here is the traceback:
```
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/b/bslydelg/anaconda3/envs/new-ndcms/bin/merlin", line 33, in <module>
    sys.exit(load_entry_point('merlin', 'console_scripts', 'merlin')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/b/bslydelg/merlin/merlin/main.py", line 1171, in main
    args.func(args)
  File "/afs/crc.nd.edu/user/b/bslydelg/merlin/merlin/main.py", line 356, in query_study
    router.query_study(spec)
  File "/afs/crc.nd.edu/user/b/bslydelg/merlin/merlin/router.py", line 170, in query_study
    query_taskvine_study(spec)
  File "/afs/crc.nd.edu/user/b/bslydelg/merlin/merlin/study/vineadapter.py", line 153, in query_taskvine_study
    redis_conn.ping()
  File "/afs/crc.nd.edu/user/b/bslydelg/anaconda3/envs/new-ndcms/lib/python3.11/site-packages/redis/commands/core.py", line 1208, in ping
    return self.execute_command("PING", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/b/bslydelg/anaconda3/envs/new-ndcms/lib/python3.11/site-packages/redis/client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/b/bslydelg/anaconda3/envs/new-ndcms/lib/python3.11/site-packages/redis/connection.py", line 1074, in get_connection
    connection.connect()
  File "/afs/crc.nd.edu/user/b/bslydelg/anaconda3/envs/new-ndcms/lib/python3.11/site-packages/redis/connection.py", line 277, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/b/bslydelg/anaconda3/envs/new-ndcms/lib/python3.11/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/afs/crc.nd.edu/user/b/bslydelg/anaconda3/envs/new-ndcms/lib/python3.11/site-packages/redis/connection.py", line 278, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/b/bslydelg/anaconda3/envs/new-ndcms/lib/python3.11/site-packages/redis/connection.py", line 748, in _connect
    sslsock = context.wrap_socket(sock, server_hostname=self.host)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/b/bslydelg/anaconda3/envs/new-ndcms/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/b/bslydelg/anaconda3/envs/new-ndcms/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/afs/crc.nd.edu/user/b/bslydelg/anaconda3/envs/new-ndcms/lib/python3.11/ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
```

A smaller issue with the Redis Connection Manager that Ive been able to circumvent:
`ssl_cert_reqs=CONFIG.results_backend.cert_reqs`
causes this error:
`[2024-09-11 14:31:56: ERROR] 'types.SimpleNamespace' object has no attribute 'cert_reqs'`
I just set it to `"none"` to avoid the error

This is the contents of my app.yaml file:
```
broker:
  name: redis
  password: /afs/crc.nd.edu/user/b/bslydelg/merlin/merlin/examples/taskvine/merlin_server/redis.pass
  port: '6379'
  server: 127.0.0.1
  username: default
celery:
  override:
    visibility_timeout: 86400
container:
  config: redis.conf
  config_dir: ./merlin_server/
  format: singularity
  image: redis_latest.sif
  image_type: redis
  pass_file: redis.pass
  pfile: merlin_server.pf
  url: docker://redis
  user_file: redis.users
process:
  kill: kill {pid}
  status: pgrep -P {pid}
results_backend:
  db_num: 0
  dbname: mlsi
  encryption_key: ~/.merlin/encrypt_data_key
  name: redis
  password: /afs/crc.nd.edu/user/b/bslydelg/merlin/merlin/examples/taskvine/merlin_server/redis.pass
  port: '6379'
  server: 127.0.0.1
  username: default                                           
```

**Comment by bgunnar5** [comment]
In the `results_backend` and `broker` sections of your app.yaml file, try setting `cert_reqs: none`. This is typically what's done when setting this connection up at the lab too so that's nothing out of the ordinary. You may also need to set `name: rediss` (with 2 s's).

I'm curious, did you set up a redis server at Notre Dame using the `merlin server` command or did you do it all manually? If you did it manually, are you hosting the server through a container on your own machine?
